language: node_js
node_js:
- 12
- 13
- 14
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_script:
- npm i -g
script:
- npm run test
deploy:
  provider: npm
  email: tadataku.lab@gmail.com
  api_key:
    secure: Uwsf2tL3i8P5/ooJk2dDH/Kg21q7C0tcAmHjs/krONYTrodYdtOfDO1PsVY6hf2wrxth/sxtpDOW6wD0jernkZAJUOdYOkyqYm8kVnQYmSVObxqxBpN/R6/RpmOpwTBEmTRKVYTXwwHU38jpO1bc6+Fn+ufcWD5i2jkGVmhMFiT7HNsBmn1zW6MZU5dn28+OY2m4cisaH/tnXCw2k9mN5xpV4U27aXXTkZckSW4CAfwm9VLAJGSwyZUFGEWAcP4oWqvo97dsJ4sZUIvukW65EK3H46cmGhnB7z+DOzpkvtjx+S2/mEnBCVtd79GKsbjI3xj+BR9G4Wz8ffCpF07ahf6fesOQkp2Uzdjk08yevGLN85RRpRupAPLv71MHa7ZqeF6O/j7NVJLVCU6MxHg06fpHPEKEr3MW0rqKq48hTVUXNmvAxp+qFJFP5G2cuGmide66G8TVU8IoT7WcGZZpNK5uBdzK8wT3cIMf0fqnvv6yctNkeOdO9oiQx6/4pG0F9IL4vwNPXy4KumZFA6a2fJYV0V96vMWkZCsQuDEx7+7+kXlVEFLioW8gdTJa5KEWvEMhIuA8AHCPn4lueBuze4pY4234fjZVDLlzELExBG+2Mz/9ELTsNZdQJzlRpKUFgaifGEVMS4P9wScWVpOCRSINZG2GMMqrD6uG79BPt8s=
  on:
    tags: true
  skip_cleanup: 'true'
