language: node_js
node_js:
- 12
- 13
- 14
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_script:
- npm i -g
script:
- npm run test
deploy:
  provider: npm
  email: tadataku.lab@gmail.com
  api_key:
    secure: hlPNcuaV7ELfKyI5RxWiYfQ2w8qiBjZJHqZC9oW3vCja29D3TmFv3QETgVOB6yoorb+Yt2xIjfv86lWvgb/wG64gHJwbe0msHflD1Qb9THo6gS16MV6w/k8raWzTjxCO511eLRZRYg2ffuAz1t7jvpw3uzI3V1wTxlH1dMnl0P3xoKLI8fVByB7hcOtAYlcYedxP0QmFIFo2L0AbYgMvlsXt/e/2xrmDE94GsjqPmCJs6/nIA6MyNqz29nwHbeWMJ0GxJDZiIISkwmuWRF+28eSoLja8+jVvqk60Yx316n60mo36akwnA8GEEvpJ+jIcdk12oooAzCdW1Ejtw8L/Lk5xLA3cxZj6Ahhxhl4pBvj0P5U3Dgyfi3O99Jb/cTEIKrjkcKUHHQDos2TtnsgQsiJ+Ct0aCp421lX5t2+XMEFklShWR4WyFy3TZbtZB6WCxvbCUa5/0XZZsdXq7VbgkjIK5Ep/Mjv/JCtmfN6RSJwmEEWME3UtJ3xI7qJ6wtGMlYhJmZVC5eR20SU+U1UhojAfUGDw/pf29ALjsxDV4Z3IyqHBu9ONDTRx8CTUXRZlBpnd1wV11ATS8qllQZuOXXhZqAYz9ImXSewSDapw1CG0vf3TVMRFPQwLX+4C5Nt+NnBqhIejS+Qq3BawEx0568GIMKlghB1eFmThCAaka+M=
  on:
    tags: true
    repo: playpuppy/puppy-editor
