language: node_js
node_js:
- 12
- 13
- 14
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_script:
- npm i -g
script:
- npm run test
deploy:
  provider: npm
  email: tadataku.lab@gmail.com
  api_key:
    secure: MBhJpKBKpdDxtzKTr2/NR7AeN96lzavU3SwvghS/pf/8D7m36BkyhrjhJjja2JKtbQIFIVhDX24TYxx7fzVFoOIMKrvCs8mFhG1Ji9DbV9Y3UB/uLv1Ik3JlZ/42qi2S83yYSW7CtVBvtCfyInr4KouzwbIV3QI7Z/1YeuPdwNrPRlOYi3cIQ6Kbj5Nwca6U7k+OUpMs8wDPWRJpPW47sSdrb6ntfddjhF9nSVqgJAUJACdYTNJ2NvZ+/JfI3QQpnUaHGvuw3I6WcKJ1VYMJ5GDGmAf/RTjOa1haco6xmn5KKQG4VFaZXKWCORD5rceYWR/R0FagyF16kY17e4hbddTdIsUoz19g9hVxFjy5sWIcYeLKzA6AIY7+lwM2KH4+3KX8LMwr8nPCL7MrUF+IlB/yJ6PwaMnIUR3JArV5Ip1KbS0fOQ01WCO1QNw15JREG5TTafhgO6rYrJda2ZJl0iByPnomHYYpupNrKpGdLIYEWiJleMRM4QM9vSVL6aKTuw2gT7E+qP7N0Rn79hVjDLDyYDcsLp/OaWvOeYuNJcBagFtuv2f4zgUwtmRO/0ov3E6/oeKRdbj8An8b7IAKJPE2T3/1uy0mlqA4yM7EIYsLQPjY0BBfAJq+gSyH4ofsgO9MPH6XQ8Py7zQ4N54p1m/Ix2SO2Xk9BG1qta0I11E=
  on:
    tags: true
  skip_cleanup: 'true'
